import math
print('Olá')
PREDUNUNTA = input('Vai colar na prova?:')
if PREDUNUNTA == 'sim':
    exit()
if PREDUNUNTA == 'não':
    num1 = float(input('Escolha um número:'))
    num2 = float(input('Escolha outro número:'.format(num1)))
    print('a soma de {} e {} é igual a {}'.format(num1, num2, num1 + num2))
    print('a subtração de {} e {} é igual a {}'.format(num1, num2, num1 - num2))
    print('a multiplicação de {} e {} é igual a {}'.format(num1, num2, num1 * num2))
print('a divisão de {} e {} é igual a {:.6f}'.format(num1, num2, num1 / num2))
pergunta = input('Se quiser mais operções digite sim,se não quiser mais digite não:')
if pergunta == 'não':
     print('finalizando o sistema...')
     exit()
elif pergunta == 'sim':
    print('a raiz quadrada de {} é {:.3f}, já a raiz quadrada de {} é {:.3f}'.format(num1, math.sqrt(num1), num2,math.sqrt(num2)))
    print('a divisão inteira de {} e {} é igual a {}'.format(num1, num2, num1 // num2))
    print('o resto da divisão de {} e {} é igual a {}'.format(num1, num2, num1 % num2))
pergunta2 = input('Quer ver a potênciação de {} e {}?(coloque tudo minúsculo pode dar erro por o número ser muito grande):'.format(num1,num2))
if pergunta2 == 'não':
    print('finalizando o sistema....')
    exit()
if pergunta2 == 'sim':
    print('o número {} elevado a {} é igual a {}'.format(num1, num2, num1 ** num2))
preduna = input('Quer ver a tabuada do {} e do {}?:'.format(num1,num2))
if preduna == 'não':
    print('finalizando o sistema..')
    exit()
if preduna =='sim':
    print('=========tabuada do {}========'.format(num1))
    print('{} X {} = {}'.format(num1,1,num1 * 1))
    print('{} X {} = {}'.format(num1,2,num1 * 2))
    print('{} X {} = {}'.format(num1,3,num1 * 3))
    print('{} X {} = {}'.format(num1,4,num1 * 4))
    print('{} X {} = {}'.format(num1,5,num1 * 5))
    print('{} X {} = {}'.format(num1,6,num1 * 6))
    print('{} X {} = {}'.format(num1,7,num1 * 7))
    print('{} X {} = {}'.format(num1,8,num1 * 8))
    print('{} X {} = {}'.format(num1,9,num1 * 9))
    print('{} X {} = {}'.format(num1,10,num1 * 10))
    print('============= tabuada do {}============'.format(num2))
    print('{} X {} = {}'.format(num2, 1, num2 * 1))
    print('{} X {} = {}'.format(num2, 2, num2 * 2))
    print('{} X {} = {}'.format(num2, 3, num2 * 3))
    print('{} X {} = {}'.format(num2, 4, num2 * 4))
    print('{} X {} = {}'.format(num2, 5, num2 * 5))
    print('{} X {} = {}'.format(num2, 6, num2 * 6))
    print('{} X {} = {}'.format(num2, 7, num2 * 7))
    print('{} X {} = {}'.format(num2, 8, num2 * 8))
    print('{} X {} = {}'.format(num2, 9, num2 * 9))
    print('{} X {} = {}'.format(num2, 10, num2 * 10))
    prdyru = input('QUER FECHAR MESMO?:')
